# no copy is needed if not run as a standalone
# vi plugins/tripleo-undercloud/tasks/images/repos.yml +18
#- name: copy repo file from undercloud machine to overcloud nodes
#  synchronize: src=/etc/yum.repos.d/patched_rpms.repo dest=/etc/yum.repos.d/patched_rpms.repo
#  delegate_to: undercloud-0
  
#- name: copy rpm files from undercloud machine to overcloud nodes
#  synchronize: src=/patched_rpms dest=/patched_rpms
#  delegate_to: undercloud-0
- name: Copy container-check.py script to overcloud
  copy:
      src: "{{ role_path }}/../../container-check.py"
      dest: /tmp/container-check.py
      mode: 0755
      force: yes

- name: Copy docker-images.yaml to overcloud
  copy:
      src: '/tmp/docker-images.yaml'
      dest: /tmp/docker-images.yaml
      mode: 0755
      force: yes

- name: leave only component related lines (capitalize the first character)
  shell: grep -E '{{install.component.name | capitalize}}|parameter_defaults' /tmp/docker-images.yaml  > /tmp/docker-images-filtered.yaml

- name: run container update
  shell: python /tmp/container-check.py --containers /tmp/docker-imagesi-filtered.yaml --update

- name: Restart component services
  shell: systemctl restart openstack-{{ install.component.name }}\*
